name: Build project

on: 
  workflow_dispatch: {}
  push:

jobs:
  buildForWindowsBasedPlatforms:
    runs-on: self-hosted
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Build
      - name: Build
        shell: bash
        run: ./BashScripts/build.sh

      # Remove unnecessary folder
      - name: Remove DontShipIt folder
        shell: bash
        run: ./BashScripts/removeDontShipItFolder.sh

      # Output
      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: ${{ github.workspace }}/Builds/Win64/